apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # Exposes the service on port 80
      targetPort: 80  # Forwards traffic to container port 80
  type: LoadBalancer  # Exposes the service with an external IP
